{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "librechat-admin-panel.secretName" . }}
  labels:
    {{- include "librechat-admin-panel.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.secret.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.secret.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
